#!/usr/bin/env python3
"""Generate flat TelegramBotClient convenience wrappers for every operation.

Reads the patched OpenAPI spec and emits committed Swift files into
Sources/TelegramBotKit/Generated/:
  - TelegramBotClient+<Group>.swift  — one flat method per operation,
    unwrapping the {ok, result} envelope and mapping undocumented responses
    to TelegramAPIError
  - UpdateKind.swift                 — enum of Update kinds (allowed_updates)

The script hard-fails on any schema shape it cannot classify, so spec drift
surfaces as a loud generation error instead of a silently wrong wrapper.

Usage: generate-client.py <patched-spec.json> <output-directory>
"""

import json
import sys
import textwrap

SWIFT_KEYWORD_PROPS = {"type": "_type"}

HEADER = """\
// Generated by Scripts/generate-client.py — do not edit.
// Regenerate with Scripts/generate-api.sh.

import Foundation
import OpenAPIRuntime
import TelegramBotAPI

"""


def camel(name):
    parts = name.split("_")
    ident = parts[0] + "".join(w[:1].upper() + w[1:] for w in parts[1:])
    return SWIFT_KEYWORD_PROPS.get(ident, ident)


def upper_camel(name):
    ident = camel(name)
    return ident[:1].upper() + ident[1:]


class Generator:
    def __init__(self, spec):
        self.spec = spec
        self.schemas = spec["components"]["schemas"]
        self.counts = {
            "ops": 0,
            "query": 0,
            "json": 0,
            "multipart": 0,
            "empty": 0,
            "file_input": 0,
            "parse_mode": 0,
            "chat_action": 0,
            "array_parts": 0,
        }

    # --- schema classification -------------------------------------------

    def component_is_scalar(self, name):
        schema = self.schemas[name]
        t = schema.get("type")
        if t in ("string", "integer", "boolean", "number"):
            return True
        one_of = schema.get("oneOf")
        if one_of and all(e.get("type") in ("string", "integer") for e in one_of):
            return True
        return False

    def swift_type(self, schema, where):
        if "$ref" in schema:
            return "Components.Schemas." + schema["$ref"].split("/")[-1]
        t = schema.get("type")
        if t == "string":
            return "Swift.String"
        if t == "integer":
            assert schema.get("format") == "int64", f"non-int64 integer at {where}"
            return "Swift.Int64"
        if t == "boolean":
            return "Swift.Bool"
        if t == "number":
            return "Swift.Double"
        if t == "array":
            return "[" + self.swift_type(schema["items"], where + "[]") + "]"
        sys.exit(f"generate-client: unclassified schema at {where}: {schema}")

    def is_file_input(self, schema):
        one_of = schema.get("oneOf")
        if one_of and len(one_of) == 2:
            refs = [e.get("$ref", "") for e in one_of]
            types = [e.get("type") for e in one_of]
            if any(r.endswith("/InputFile") for r in refs) and "string" in types:
                return True
        if schema.get("$ref", "").endswith("/InputFile"):
            return True
        return False

    # --- parameter model --------------------------------------------------

    def make_param(self, op_id, wire, schema, required):
        """Returns a dict describing one wrapper parameter."""
        label = camel(wire)
        kind = "plain"
        swift = None
        if self.is_file_input(schema):
            kind = "file"
            swift = "FileInput"
            self.counts["file_input"] += 1
        elif wire == "parse_mode" and schema.get("type") == "string":
            kind = "parse_mode"
            swift = "ParseMode"
            self.counts["parse_mode"] += 1
        elif op_id == "sendChatAction" and wire == "action":
            kind = "chat_action"
            swift = "ChatAction"
            self.counts["chat_action"] += 1
        elif schema.get("type") == "array":
            kind = "array"
            swift = self.swift_type(schema, f"{op_id}.{wire}")
        elif "$ref" in schema:
            ref = schema["$ref"].split("/")[-1]
            kind = "scalar_ref" if self.component_is_scalar(ref) else "object"
            swift = "Components.Schemas." + ref
        else:
            swift = self.swift_type(schema, f"{op_id}.{wire}")
        return {
            "wire": wire,
            "label": label,
            "swift": swift,
            "required": required,
            "kind": kind,
            "schema": schema,
        }

    def signature(self, params):
        ordered = [p for p in params if p["required"]] + [
            p for p in params if not p["required"]
        ]
        pieces = []
        for p in ordered:
            if p["required"]:
                pieces.append(f"{p['label']}: {p['swift']}")
            else:
                pieces.append(f"{p['label']}: {p['swift']}? = nil")
        return ", ".join(pieces)

    # --- result handling --------------------------------------------------

    def result_info(self, op):
        """Returns (swift_return_type, unwrap_kind)."""
        schema = op["responses"]["200"]["content"]["application/json"]["schema"]
        result = schema["properties"]["result"]
        one_of = result.get("oneOf")
        if one_of:
            refs = [e.get("$ref", "").split("/")[-1] for e in one_of]
            types = [e.get("type") for e in one_of]
            assert refs[0] == "Message" and "boolean" in types, (
                f"unexpected result oneOf in {op['operationId']}: {result}"
            )
            return "Components.Schemas.Message?", "message_or_bool"
        return self.swift_type(result, op["operationId"] + ".result"), "plain"

    def unwrap_lines(self, op_id, unwrap_kind):
        if unwrap_kind == "message_or_bool":
            ok_lines = [
                "        case let .ok(ok):",
                "            switch try ok.body.json.result {",
                "            case let .Message(message): return message",
                "            case .case2: return nil",
                "            }",
            ]
        else:
            ok_lines = [
                "        case let .ok(ok):",
                "            return try ok.body.json.result",
            ]
        return ok_lines + [
            "        case let .undocumented(statusCode, payload):",
            "            throw await TelegramAPIError.undocumented(",
            f'                operation: "{op_id}", statusCode: statusCode, payload: payload',
            "            )",
        ]

    def doc_comment(self, op):
        description = op.get("description") or op.get("summary") or ""
        first = description.strip().split("\n\n")[0].replace("\n", " ").strip()
        if len(first) > 500:
            first = first[:497] + "..."
        if not first:
            return []
        return [f"    /// {line}" for line in textwrap.wrap(first, width=96)]

    # --- pacing -----------------------------------------------------------

    def pace_line(self, op_id, params):
        if op_id == "getUpdates":
            return None
        chat = next((p for p in params if p["wire"] == "chat_id"), None)
        if chat is None:
            return None
        label = chat["label"]
        if chat["swift"].endswith("ChatId"):
            expr = label
        elif chat["required"]:
            expr = f".id({label})"
        else:
            expr = f"{label}.map(ChatId.id)"
        return f"        try await self.pace(chatId: {expr})"

    # --- templates --------------------------------------------------------

    def emit_query_op(self, op_id, op):
        self.counts["query"] += 1
        u = upper_camel(op_id)
        params = [
            self.make_param(op_id, par["name"], par["schema"], par.get("required", False))
            for par in op.get("parameters", [])
        ]
        for p in params:
            assert p["kind"] in ("plain", "scalar_ref", "array", "object"), (
                f"unsupported query param kind {p['kind']} in {op_id}"
            )
        return_type, unwrap = self.result_info(op)
        lines = self.doc_comment(op)
        lines.append("    @discardableResult")
        lines.append(
            f"    func {op_id}({self.signature(params)}) async throws -> {return_type} {{"
        )
        pace = self.pace_line(op_id, params)
        if pace:
            lines.append(pace)
        if params:
            fields = ", ".join(f"{p['label']}: {p['label']}" for p in params)
            lines.append(
                f"        let output = try await self.api.{op_id}(.init(query: .init({fields})))"
            )
        else:
            lines.append(f"        let output = try await self.api.{op_id}(.init())")
        lines.append("        switch output {")
        lines.extend(self.unwrap_lines(op_id, unwrap))
        lines.append("        }")
        lines.append("    }")
        return lines

    def emit_empty_op(self, op_id, op):
        self.counts["empty"] += 1
        return_type, unwrap = self.result_info(op)
        lines = self.doc_comment(op)
        lines.append("    @discardableResult")
        lines.append(f"    func {op_id}() async throws -> {return_type} {{")
        lines.append(f"        let output = try await self.api.{op_id}(.init())")
        lines.append("        switch output {")
        lines.extend(self.unwrap_lines(op_id, unwrap))
        lines.append("        }")
        lines.append("    }")
        return lines

    def json_field_expr(self, p):
        if p["kind"] == "parse_mode":
            return f"{p['label']}?.rawValue" if not p["required"] else f"{p['label']}.rawValue"
        if p["kind"] == "chat_action":
            return f"{p['label']}.rawValue"
        return p["label"]

    def emit_json_op(self, op_id, op, body_schema):
        self.counts["json"] += 1
        props = body_schema.get("properties", {})
        required = set(body_schema.get("required", []))
        params = [
            self.make_param(op_id, wire, schema, wire in required)
            for wire, schema in props.items()
        ]
        for p in params:
            assert p["kind"] != "file", f"file param in JSON body of {op_id}"
        return_type, unwrap = self.result_info(op)
        lines = self.doc_comment(op)
        lines.append("    @discardableResult")
        lines.append(
            f"    func {op_id}({self.signature(params)}) async throws -> {return_type} {{"
        )
        pace = self.pace_line(op_id, params)
        if pace:
            lines.append(pace)
        fields = ",\n".join(
            f"            {p['label']}: {self.json_field_expr(p)}" for p in params
        )
        lines.append(f"        let output = try await self.api.{op_id}(.init(body: .json(.init(")
        lines.append(fields)
        lines.append("        ))))")
        lines.append("        switch output {")
        lines.extend(self.unwrap_lines(op_id, unwrap))
        lines.append("        }")
        lines.append("    }")
        return lines

    def multipart_part_lines(self, op_id, u, p, escape_case):
        """Swift statements appending one part for parameter p."""
        label = p["label"]
        case = p["label"]
        if p["kind"] == "file":
            expr = f"parts.append(.{case}(Self.filePart({label}) {{ .init(body: $0) }}))"
        elif p["kind"] == "parse_mode":
            expr = f"parts.append(.{case}(.init(payload: .init(body: HTTPBody({label}.rawValue)))))"
        elif p["kind"] == "chat_action":
            expr = f"parts.append(.{case}(.init(payload: .init(body: HTTPBody({label}.rawValue)))))"
        elif p["kind"] == "array":
            self.counts["array_parts"] += 1
            if escape_case == "additionalProperties":
                expr = (
                    f"parts.append(.additionalProperties(.init("
                    f"payload: try Self.jsonBody({label}), name: \"{p['wire']}\")))"
                )
            else:
                expr = (
                    f"parts.append(.undocumented(.init("
                    f"name: \"{p['wire']}\", headerFields: [:], body: try Self.jsonBody({label}))))"
                )
        elif p["kind"] == "object":
            expr = f"parts.append(.{case}(.init(payload: .init(body: {label}))))"
        elif p["kind"] == "scalar_ref":
            assert p["swift"].endswith("ChatId"), f"unexpected scalar ref in {op_id}: {p}"
            expr = f"parts.append(.{case}(.init(payload: .init(body: Self.body(for: {label})))))"
        elif p["swift"] == "Swift.String":
            expr = f"parts.append(.{case}(.init(payload: .init(body: HTTPBody({label})))))"
        elif p["swift"] in ("Swift.Int64", "Swift.Double"):
            expr = f"parts.append(.{case}(.init(payload: .init(body: HTTPBody(String({label}))))))"
        elif p["swift"] == "Swift.Bool":
            expr = f"parts.append(.{case}(.init(payload: .init(body: HTTPBody({label} ? \"true\" : \"false\")))))"
        else:
            sys.exit(f"generate-client: unhandled multipart param in {op_id}: {p}")

        if p["required"]:
            return [f"        {expr}"]
        return [f"        if let {label} {{", f"            {expr}", "        }"]

    def emit_multipart_op(self, op_id, op, body_schema):
        self.counts["multipart"] += 1
        u = upper_camel(op_id)
        props = body_schema.get("properties", {})
        required = set(body_schema.get("required", []))
        escape_case = (
            "additionalProperties"
            if "additionalProperties" in body_schema
            else "undocumented"
        )
        params = [
            self.make_param(op_id, wire, schema, wire in required)
            for wire, schema in props.items()
        ]
        return_type, unwrap = self.result_info(op)
        lines = self.doc_comment(op)
        lines.append("    @discardableResult")
        lines.append(
            f"    func {op_id}({self.signature(params)}) async throws -> {return_type} {{"
        )
        pace = self.pace_line(op_id, params)
        if pace:
            lines.append(pace)
        lines.append(
            f"        var parts: [Operations.{u}.Input.Body.MultipartFormPayload] = []"
        )
        for p in params:
            lines.extend(self.multipart_part_lines(op_id, u, p, escape_case))
        lines.append(
            f"        let output = try await self.api.{op_id}(.init(body: .multipartForm(.init(parts))))"
        )
        lines.append("        switch output {")
        lines.extend(self.unwrap_lines(op_id, unwrap))
        lines.append("        }")
        lines.append("    }")
        return lines

    # --- grouping ---------------------------------------------------------

    @staticmethod
    def group_for(op_id):
        lowered = op_id.lower()
        if op_id in (
            "getUpdates", "setWebhook", "deleteWebhook", "getWebhookInfo",
            "getMe", "logOut", "close",
        ):
            return "Updates"
        if "sticker" in lowered:
            return "Stickers"
        if any(k in lowered for k in ("inline", "webapp", "guestquery")):
            return "Inline"
        if any(k in lowered for k in (
            "invoice", "shipping", "precheckout", "star", "gift", "payment",
            "paidmedia", "subscription",
        )):
            return "Payments"
        if "chat" in lowered or "forum" in lowered:
            return "Chats"
        if any(k in lowered for k in (
            "send", "edit", "delete", "forward", "copy", "stop", "message",
            "poll", "story", "reaction", "dice", "media",
        )):
            return "Messaging"
        return "Misc"

    # --- entry point ------------------------------------------------------

    def generate(self):
        groups = {}
        for path, ops in self.spec["paths"].items():
            for method, op in ops.items():
                op_id = op["operationId"]
                self.counts["ops"] += 1
                body = op.get("requestBody")
                if method == "get":
                    lines = self.emit_query_op(op_id, op)
                elif body is None:
                    lines = self.emit_empty_op(op_id, op)
                elif "application/json" in body["content"]:
                    lines = self.emit_json_op(
                        op_id, op, body["content"]["application/json"]["schema"]
                    )
                elif "multipart/form-data" in body["content"]:
                    lines = self.emit_multipart_op(
                        op_id, op, body["content"]["multipart/form-data"]["schema"]
                    )
                else:
                    sys.exit(f"generate-client: unknown body content in {op_id}")
                groups.setdefault(self.group_for(op_id), []).append("\n".join(lines))

        files = {}
        for group, methods in sorted(groups.items()):
            body = HEADER
            body += f"public extension TelegramBotClient {{\n"
            body += "\n\n".join(methods)
            body += "\n}\n"
            files[f"TelegramBotClient+{group}.swift"] = body
        files["UpdateKind.swift"] = self.generate_update_kind()
        return files

    def generate_update_kind(self):
        update = self.schemas["Update"]
        kinds = [name for name in update["properties"] if name != "update_id"]
        lines = [
            "// Generated by Scripts/generate-client.py — do not edit.",
            "// Regenerate with Scripts/generate-api.sh.",
            "",
            "import TelegramBotAPI",
            "",
            "/// A kind of incoming Telegram update; raw values are the wire",
            "/// strings accepted by `allowed_updates`.",
            "public enum UpdateKind: String, CaseIterable, Sendable, Hashable {",
        ]
        for wire in kinds:
            lines.append(f'    case {camel(wire)} = "{wire}"')
        lines.append("}")
        lines.append("")
        lines.append("public extension Update {")
        lines.append("    /// The kind of this update, when it carries a known payload.")
        lines.append("    var kind: UpdateKind? {")
        for wire in kinds:
            lines.append(
                f"        if self.{camel(wire)} != nil {{ return .{camel(wire)} }}"
            )
        lines.append("        return nil")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def verify_counts(self):
        expectations = {
            "ops": (185, 220),
            "query": (0, 5),
            "json": (130, 170),
            "multipart": (30, 40),
            "empty": (2, 12),
            "file_input": (17, 30),
            "parse_mode": (10, 60),
            "chat_action": (1, 1),
            "array_parts": (20, 40),
        }
        for key, (low, high) in expectations.items():
            value = self.counts[key]
            if not (low <= value <= high):
                sys.exit(
                    f"generate-client: count '{key}'={value} outside [{low}, {high}]"
                    " — spec shape changed?"
                )


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    spec_path, out_dir = sys.argv[1], sys.argv[2]
    spec = json.load(open(spec_path))
    generator = Generator(spec)
    files = generator.generate()
    generator.verify_counts()
    import os

    os.makedirs(out_dir, exist_ok=True)
    for name, content in sorted(files.items()):
        with open(os.path.join(out_dir, name), "w") as handle:
            handle.write(content)
    print(
        "generate-client:",
        ", ".join(f"{k}={v}" for k, v in sorted(generator.counts.items())),
        f"→ {len(files)} files",
    )


if __name__ == "__main__":
    main()
